### ISSUE TITLE
Unauthorized DHIS2 error when trying to write data

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/godata-interoperability#12]
## Describe the bug
Flow #6 (Go.Data --> DHIS2) was working before... so I think something changed in the COVID-19 DHIS2 instance we are connecting with. Can you please investigate and determine if we need to change our job? Perhaps to write to a different `dataValueSet`? 

Please let me know what you find so that we can determine the best way to proceed for this demo. This will be shared with DHIS2 team members & other WHO folks, so I would love to have a working flow to demo to them. 

See here for original mapping specs: https://docs.google.com/spreadsheets/d/1SNx5wB818ikveaVhHqW9c4N05leL1WGZulsdC_BJj70/edit#gid=1214788032

## To Reproduce
Here is the run failure: https://www.openfn.org/projects/p5amme/runs/rg54m9xg
Re-run flow 6 jobs to trigger: https://www.openfn.org/projects/p5amme/jobs/jvg3br

### expression.js
https://github.com/OpenFn/godata-interoperability/blob/master/jobs/6b-importDHIS2.js

### state.json
See LP for `DHIS2 Covid-19 Demo Org`

## Expected behavior
We want to count cases in Go.Data, and upload this aggregate value to a `dataValueSet` in DHIS2.

**Comment by taylordowns2000** [comment]
@aleksa-krolls , is this issue still open? Sounded like dhis2 configuration troubles related to the daily-changing-and-refreshing play server. Can we close?
