### ISSUE TITLE
Upsert cases from Kobo data form submission

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/godata-interoperability#2]
## Background
Common use case is to integrate mobile apps with Go.Data to streamline case registration. We want to demo a Kobo -> Go.Data flow for this use case. 

## Request
Create 1 job that will upsert Go.Data `Cases` based on incoming Kobo data. See [`Mappings-Flow4`](https://docs.google.com/spreadsheets/d/180Y4l9CUJjQUFZJObLStgkHD_lWnCZk8pkEqA-ADdek/edit#gid=1031366813) for field mapping specs. 

Configure the job on Prod here: https://www.openfn.org/projects/3037/jobs/3851

## state
See LP for `Go.Data Demo Site` (this is a demo site, so feel free to create new test case data)
See Kobo submission here: https://github.com/OpenFn/godata-interoperability/blob/master/sampleData/coxBazarKoboResponse%20.json

## expression
https://github.com/OpenFn/godata-interoperability/blob/f3fe86d20eaafc9ff87e01895c12c9a78ded2d6c/jobs/4-upsertCases.js#L1

## adaptor
Use new `upsertCases()` function in `language-godata` to upsert Cases via `visual_Id`

## output
Upsert 1 Case record in Go.Data related to this Outbreak: http://who-stable.clarisoft.com/outbreaks/d4eecdeb-252d-44ec-bf76-515e005e03bd/view

**Comment by aleksa-krolls** [comment]
@taylordowns2000 @lakhassane here is the first Go.Data job that is ready to go. More specs coming later today!

**Comment by taylordowns2000** [comment]
@aleksa-krolls , I'm getting a 404 on that job URL on prod. Do I have access to this project?

**Comment by taylordowns2000** [comment]
back in icebox. done offline but needs to be hooked up to the real job on prod once the new adaptor is deployed.

**Comment by taylordowns2000** [comment]
![image.png](https://images.zenhubusercontent.com/566ac5e0638e718c995f5356/b5681d75-6458-4461-bd1a-8500c1b02a29)

**Comment by aleksa-krolls** [comment]
@lakhassane same thing - can you please log the final state/ output we send to Go.Data for `4-upsertCases.js`? 

You can re-run this to test: https://www.openfn.org/projects/p5amme/runs/raaarajx

**Comment by lakhassane** [comment]
@aleksa-krolls log added here
Check run: https://www.openfn.org/projects/p5amme/runs/rzdd4d6b
