### ISSUE TITLE
Upsert health facilities as Locations in Go.Data

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/godata-interoperability#4]
## Background, context, and business value
For one of the Go.Data reference implementation flows, we want to import Health Facility data from an external data source into Go.Data to fast-track system setup and ensure Go.Data information is linked to shared records on hospital locations. We've already determined how to fetch the health facility data, but now need to map it to Go.Data. 

## The specific request, in as few words as possible
1. Add helper function to `language-godata` to support `Location` upserts
2. Write a job to upsert all `"amenity": "hospital"` locations to Go.Data - [see mapping specs for Flow5](https://docs.google.com/spreadsheets/d/180Y4l9CUJjQUFZJObLStgkHD_lWnCZk8pkEqA-ADdek/edit#gid=1783114713)

## state.json
See LP for `Go.Data Demo Site`
Bangladesh hospitals to upload: https://github.com/OpenFn/godata-interoperability/blob/master/sampleData/bangladeshHealthSites.json

## adaptor
`language-godata`

## expression.js
1 job that will run every time new locations are fetched from http://healthsites.io/

## output.json
New `Locations` upserted in Go.Data... we might need to test to verify whether to use the `PUT` or `PATCH` method. 

Please configure a job in prod and run this Message to test: https://www.openfn.org/projects/3037/messages/10446959

**Comment by lakhassane** [comment]
@aleksa-krolls are we having right value data for `coordinates` in `Go.Data` ? I am having a `500 internal server error` on `POST` with some data. 

By trying on `postman` here is the response: 
![image](https://user-images.githubusercontent.com/8411231/102691784-f3a75980-4206-11eb-99b8-dd8d7a5aadd6.png)
Here is the concerned data: 
```json
{
    "name": "Manikchari Upazila Health Complex",
    "synonyms": [
        "hospital"
    ],
    "identifiers": [
        {
            "description": "uuid",
            "code": "4598ac8e8c6d47a4a3b95d0806ca4a5d"
        }
    ],
    "geoLocation": {
        "lat": 91.84117813480628,
        "lng": 22.8501898435141
    },
    "active": true,
    "parentLocationId": "e86414e4-d91c-4ab8-be2a-720ae90b5106",
    "geographicalLevelId": "LNG_REFERENCE_DATA_CATEGORY_LOCATION_GEOGRAPHICAL_LEVEL_HOSPITAL_FACILITY"
}
```

**Comment by aleksa-krolls** [comment]
@lakhassane It looks like the `lat` and `lng` values need to be reversed so that...
```
"geoLocation": {
        "lat": 22.8501898435141,
        "lng": 91.84117813480628
    },
```

**Comment by aleksa-krolls** [comment]
@lakhassane Please link job on prod here: https://www.openfn.org/projects/p5amme/jobs/jya3k3

Then please run against this Message to test: https://www.openfn.org/projects/p5amme/messages/ma9qva7m

**Comment by aleksa-krolls** [comment]
@lakhassane This fails on prod - see run & message here: https://www.openfn.org/projects/p5amme/runs/rmkk9e4y

**Comment by aleksa-krolls** [comment]
@lakhassane Amazing, working now. Can you please update the logs to either log all of `state.data` or at least the location `name`s? Actually please log the `state.data` output sent to Go.Data... we're trying to build users' intuition on what these integrations are doing... so would be great to see what we actually post to Go.Data.
