### ISSUE TITLE
New job to get & summary Go.Data cases to report counts to DHIS2

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/godata-interoperability#7]
## Background, context, and business value
For the GoData team, we want to configure a series of reference implementations to demonstrate different integration use cases. One of these is aggregate reporting of Go.Data cases to DHIS2 (e.g., # of COVID-19 cases confirmed, # of cases hopsitalized, etc.) 
![image](https://user-images.githubusercontent.com/16758106/102584863-f6735300-410f-11eb-8ce3-1f96aebbaba4.png)

## The specific request, in as few words as possible
To demonstrate aggregate reporting from Go.Data --> DHIS2, I would like to create **Job #1** that...
1. GET `cases` from Go.Data WHERE `"classification": "LNG_REFERENCE_DATA_CATEGORY_CASE_CLASSIFICATION_CONFIRMED"` to only pull confirmed cases
2. Filter this GET request by a cursor that only fetches cases where `dateOfReporting` is in the last 24hours. Have the job automatically update this cursor every run, but also let users set a `manualCursor` to override this if desired (see what we did in `wcs` jobs). 
3. COUNT the # of Go.Data `cases` returned to calculate the summary `value`, `completeDate` and `period` (based on `dateOfReporting`) ... these 3 values will be reported to DHIS2

Then write **Job #2** using `language-dhis2` to import this summary value to DHIS2 as `DataValueSets`
1. Leverage the `language-dhis2` helper function `dataValueSet()`-> [see here](https://github.com/OpenFn/godata-interoperability/blob/master/sampleData/importDataValues) for the desired output
2. [See here](https://docs.google.com/spreadsheets/d/180Y4l9CUJjQUFZJObLStgkHD_lWnCZk8pkEqA-ADdek/edit#gid=1214788032) for the mapping specs 

## state.json
Go.Data: See LP for `Go.Data Demo Site`
DHIS2: See LP for `DHIS2 COVID-19 Demo Site`

## output.json
What should be imported successfully to DHIS2: https://github.com/OpenFn/godata-interoperability/blob/master/sampleData/importDataValues

**ImportSummary** should look something like this...
```{
    "responseType": "ImportSummary",
    "status": "SUCCESS",
    "importOptions": {
        "idSchemes": {},
        "dryRun": false,
        "async": false,
        "importStrategy": "CREATE_AND_UPDATE",
        "mergeMode": "REPLACE",
        "reportMode": "FULL",
        "skipExistingCheck": false,
        "sharing": false,
        "skipNotifications": false,
        "skipAudit": false,
        "datasetAllowsPeriods": false,
        "strictPeriods": false,
        "strictDataElements": false,
        "strictCategoryOptionCombos": false,
        "strictAttributeOptionCombos": false,
        "strictOrganisationUnits": false,
        "requireCategoryOptionCombo": false,
        "requireAttributeOptionCombo": false,
        "skipPatternValidation": false,
        "ignoreEmptyCollection": false,
        "force": false,
        "firstRowIsHeader": true,
        "skipLastUpdated": false
    },
    "description": "Import process completed successfully",
    "importCount": {
        "imported": 0,
        "updated": 1,
        "ignored": 0,
        "deleted": 0
    },
    "dataSetComplete": "2020-12-21"
}

**Comment by lakhassane** [comment]
@aleksa-krolls in jobs #1 do we know the `outbreak_id` since fetching cases is always done using an outrbreak?

**Comment by aleksa-krolls** [comment]
@lakhassane Please continue to use the same hardcoded outbreak `id: 3b5554d7-2c19-41d0-b9af-475ad25a382b` (and I will add to the mapping specs). Thanks!

**Comment by lakhassane** [comment]
@aleksa-krolls could you bring more explanation to point 3 here (`COUNT the # of Go.Data cases returned to calculate the summary value, completeDate and period (based on dateOfReporting) ... these 3 values will be reported to DHIS2`)
What are those 3 values and what do they represent?

**Comment by aleksa-krolls** [comment]
@lakhassane See the mapping spec! Ping me on Slack if you still have questions.

**Comment by aleksa-krolls** [comment]
@lakhassane This DHIS2 job fails on prod: https://www.openfn.org/projects/p5amme/runs/rj5575e3. I'm copying @chaiwa-berian in case it has anything to do with `language-dhis2`. 

Re-run the job for this Message to replicate: https://www.openfn.org/projects/p5amme/runs/rbgg8g6a

**Comment by lakhassane** [comment]
@aleksa-krolls not related to DHIS but rather my side. Corrections done. See this run: https://www.openfn.org/projects/p5amme/runs/rwaa3akb
